// 40-space board definition, clockwise from GO

const BOARD_SPACES = [
  { index: 0,  type: 'go',                 name: 'KICKOFF' },
  { index: 1,  type: 'property',           propertyId: 'auburn_tigers' },
  { index: 2,  type: 'card_commissioners', name: "Commissioner's Office" },
  { index: 3,  type: 'property',           propertyId: 'vanderbilt_commodores' },
  { index: 4,  type: 'tax_income',         name: 'Program Expenses' },
  { index: 5,  type: 'bowl_game',          propertyId: 'rose_bowl' },
  { index: 6,  type: 'property',           propertyId: 'georgia_tech' },
  { index: 7,  type: 'card_gridiron',      name: 'Gridiron Events' },
  { index: 8,  type: 'property',           propertyId: 'tennessee_volunteers' },
  { index: 9,  type: 'property',           propertyId: 'georgia_bulldogs_early' },
  { index: 10, type: 'jail_visit',         name: 'Just Visiting / NCAA Probation' },
  { index: 11, type: 'property',           propertyId: 'lsu_tigers' },
  { index: 12, type: 'tv_contract',        propertyId: 'cbs_sec_network' },
  { index: 13, type: 'property',           propertyId: 'ole_miss_rebels' },
  { index: 14, type: 'property',           propertyId: 'mississippi_state' },
  { index: 15, type: 'bowl_game',          propertyId: 'sugar_bowl' },
  { index: 16, type: 'property',           propertyId: 'florida_gators' },
  { index: 17, type: 'card_commissioners', name: "Commissioner's Office" },
  { index: 18, type: 'property',           propertyId: 'south_carolina' },
  { index: 19, type: 'property',           propertyId: 'kentucky_wildcats' },
  { index: 20, type: 'free_parking',       name: 'NIL Signing Day' },
  { index: 21, type: 'property',           propertyId: 'alabama_early' },
  { index: 22, type: 'card_gridiron',      name: 'Gridiron Events' },
  { index: 23, type: 'property',           propertyId: 'arkansas_razorbacks' },
  { index: 24, type: 'property',           propertyId: 'texas_longhorns' },
  { index: 25, type: 'bowl_game',          propertyId: 'orange_bowl' },
  { index: 26, type: 'property',           propertyId: 'florida_state' },
  { index: 27, type: 'property',           propertyId: 'miami_hurricanes' },
  { index: 28, type: 'tv_contract',        propertyId: 'espn_contract' },
  { index: 29, type: 'property',           propertyId: 'notre_dame' },
  { index: 30, type: 'go_to_jail',         name: "GO TO COMMISSIONER'S OFFICE" },
  { index: 31, type: 'property',           propertyId: 'ohio_state' },
  { index: 32, type: 'property',           propertyId: 'usc_trojans' },
  { index: 33, type: 'card_commissioners', name: "Commissioner's Office" },
  { index: 34, type: 'property',           propertyId: 'clemson_tigers' },
  { index: 35, type: 'bowl_game',          propertyId: 'cotton_bowl' },
  { index: 36, type: 'card_gridiron',      name: 'Gridiron Events' },
  { index: 37, type: 'property',           propertyId: 'georgia_bulldogs_modern' },
  { index: 38, type: 'tax_luxury',         name: 'Stadium Renovation Tax' },
  { index: 39, type: 'property',           propertyId: 'alabama_modern' },
];

module.exports = { BOARD_SPACES };
